({
  host: '0.0.0.0',
  balancer: 8000,
  protocol: 'http2',
  ports: [443],
  apiUri: '/api',
  static: {
    ext: [
      'css',
      'jpg',
      'gif',
      'png',
      'svg',
      'zip',
      'rar',
      'doc',
      'xls',
      'js',
      'tif',
      'tiff',
      'docx',
      'xlsx',
      'ico',
      'json',
      'html',
      'txt',
    ],
    disabledVirtualFolders: false,
    folders: ['/test2', '/article'],
    rootFiles: ['/favicon.ico', '/favicon.png'],
  },
  nagle: false,
  timeouts: {
    bind: 2000,
    start: 30000,
    stop: 5000,
    request: 5000,
    watch: 1000,
    test: 60000,
  },
  queue: {
    concurrency: 1000,
    size: 2000,
    timeout: 3000,
  },
  scheduler: {
    concurrency: 10,
    timeout: 3000,
  },
  workers: {
    pool: 2,
    wait: 2000,
    timeout: 5000,
  },
  cors: {
    origin: '*',
  },
});
